/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper */

#ifndef _Included_com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper
#define _Included_com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper
 * Method:    CtrlAltDel_Enable_Disable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper_CtrlAltDel_1Enable_1Disable
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper
 * Method:    TaskSwitching_Enable_Disable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper_TaskSwitching_1Enable_1Disable
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper
 * Method:    Process_Desktop
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper_Process_1Desktop
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper
 * Method:    Process_Block
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper_Process_1Block
  (JNIEnv *, jclass);

/*
 * Class:     com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper
 * Method:    Kill_Task_Mgr
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper_Kill_1Task_1Mgr
  (JNIEnv *, jclass);

/*
 * Class:     com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper
 * Method:    Hot_Keys_Enable_Disable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper_Hot_1Keys_1Enable_1Disable
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper
 * Method:    kill_printscreen_snapshot
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper_kill_1printscreen_1snapshot
  (JNIEnv *, jclass);

/*
 * Class:     com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper
 * Method:    Process_Check
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper_Process_1Check
  (JNIEnv *, jclass);

/*
 * Class:     com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper
 * Method:    Get_Blacklist_Process_No
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper_Get_1Blacklist_1Process_1No
  (JNIEnv *, jclass);

/*
 * Class:     com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper
 * Method:    Add_shortcuts
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper_Add_1shortcuts
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper
 * Method:    Rightclick_Enable_Disable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper_Rightclick_1Enable_1Disable
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper
 * Method:    Open_Close_Interface
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper_Open_1Close_1Interface
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
