/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper */

#ifndef _Included_com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper
#define _Included_com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper
 * Method:    Get_Blacklist_Process_No
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper_Get_1Blacklist_1Process_1No
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif