/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_javaunit_LockdownBrowserWrapper */

#ifndef _Included_com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper
#define _Included_com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_javaunit_LockdownBrowserWrapper
 * Method:    Hot_Keys_Enable_Disable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper_Hot_1Keys_1Enable_1Disable
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_javaunit_LockdownBrowserWrapper
 * Method:    Process_Desktop
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper_Process_1Desktop
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_javaunit_LockdownBrowserWrapper
 * Method:    Process_Block
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper_Process_1Block
  (JNIEnv *, jclass);

/*
 * Class:     com_javaunit_LockdownBrowserWrapper
 * Method:    CtrlAltDel_Enable_Disable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper_CtrlAltDel_1Enable_1Disable
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
