/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper */

#ifndef _Included_com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper
#define _Included_com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper
#ifdef __cplusplus
extern "C" {
#endif
#undef com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper_MIN_PRIORITY
#define com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper_MIN_PRIORITY 1L
#undef com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper_NORM_PRIORITY
#define com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper_NORM_PRIORITY 5L
#undef com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper_MAX_PRIORITY
#define com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper_MAX_PRIORITY 10L
/*
 * Class:     com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper
 * Method:    CtrlAltDel_Enable_Disable
 * Signature: (Z)I
 */
JNIEXPORT void JNICALL Java_com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper_CtrlAltDel_1Enable_1Disable
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper
 * Method:    TaskSwitching_Enable_Disable
 * Signature: (Z)I
 */
JNIEXPORT void JNICALL Java_com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper_TaskSwitching_1Enable_1Disable
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper
 * Method:    Process_Desktop
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT void JNICALL Java_com_ctb_tdc_bootstrap_processwrapper_LockdownBrowserWrapper_Process_1Desktop
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
